const serviceCategories = {
  Plumbing: [
    "Leak Fixing",
    "Pipe Installation",
    "Bathroom Fittings",
    "Kitchen Sink Repair",
    "Toilet Unclogging",
    "Water Tank Cleaning",
  ],
  Electrical: [
    "Wiring",
    "Fan Installation",
    "Inverter Setup",
    "Switch Board Repair",
    "Geyser Installation",
    "AC Repair",
  ],
  Cleaning: [
    "Home Cleaning",
    "Office Cleaning",
    "Sofa Cleaning",
    "Carpet Shampooing",
    "Window Cleaning",
    "Bathroom Deep Clean",
  ],
  Appliance: [
    "Washing Machine Repair",
    "Refrigerator Service",
    "Microwave Repair",
    "Chimney Cleaning",
    "Water Purifier Service",
  ],
  Painting: [
    "Interior Painting",
    "Exterior Painting",
    "Wall Texturing",
    "Pop Design",
    "Waterproof Coating",
  ],
  Carpentry: [
    "Furniture Repair",
    "Modular Kitchen Setup",
    "Door Fitting",
    "Window Frame Repair",
    "Shelf Installation",
  ],
  PestControl: [
    "Cockroach Control",
    "Termite Treatment",
    "Rodent Control",
    "Bed Bug Removal",
    "Mosquito Control",
  ],
  ITServices: [
    "Laptop Repair",
    "Network Setup",
    "Printer Troubleshooting",
    "Software Installation",
    "CCTV Installation",
  ],
  Beauty: [
    "Home Salon Service",
    "Haircut",
    "Facial",
    "Waxing",
    "Bridal Makeup",
  ],
  Fitness: [
    "Personal Trainer",
    "Yoga at Home",
    "Zumba Sessions",
    "Home Gym Setup",
  ],
  HomeSecurity: [
    "CCTV Installation",
    "Video Door Phone Setup",
    "Smart Lock Installation",
    "Alarm System Setup",
  ],
  Vehicle: ["Car Wash", "Car AC Repair", "Bike Servicing", "Wheel Alignment"],
  Gardening: [
    "Lawn Mowing",
    "Plant Setup",
    "Garden Maintenance",
    "Terrace Garden Setup",
  ],
  Moving: [
    "House Shifting",
    "Furniture Packing",
    "Office Relocation",
    "Storage Services",
  ],
  Laundry: ["Dry Cleaning", "Wash & Iron", "Curtain Cleaning", "Shoe Cleaning"],
  Education: [
    "Home Tutor",
    "Language Classes",
    "Music Lessons",
    "Competitive Exam Prep",
  ],
  EventManagement: [
    "Birthday Decoration",
    "Wedding Planning",
    "Corporate Event Setup",
    "Photography & Videography",
  ],
  Babysitting: [
    "Full-Day Nanny",
    "Hourly Babysitting",
    "Infant Care",
    "After-School Help",
  ],
  PetCare: ["Dog Walking", "Pet Grooming", "Pet Training", "Veterinary Visits"],
  InteriorDesign: [
    "Modular Kitchen",
    "False Ceiling Design",
    "2D/3D Layout Planning",
    "Home Renovation Consulting",
  ],
  Mechanic: [
    "Engine Diagnosis",
    "Brake Repair",
    "Oil Change",
    "Battery Replacement",
    "Suspension Work",
  ],
  Tutoring: [
    "Maths Tuition",
    "Science Tuition",
    "English Coaching",
    "Coding Classes",
    "Exam Doubt Sessions",
  ],
};
export default serviceCategories;
